### ISSUE TITLE
Freesound API out of date

### ISSUE THREAD

**Issue by Mestelan** [overtone/overtone#333]
As mentioned by Joakim on the mailing list, the Freesound API no longer responds.

    --> Asset not cached - starting download...
    --> Downloading file  - http://www.freesound.org/api/sounds/[2086]?api_key=47efd585321048819a2328721507ee23
      Download timed out. Retry 1: http://www.freesound.org/api/sounds/[2086]?api_key=47efd585321048819a2328721507ee23

When submitting the URL in a browser, one gets this error message:
{
    "status_code": 410,
    "explanation": "Freesound APIv1 has reached its end of life and is no longer available. Please, upgrade to Freesound APIv2. More information: http://www.freesound.org/docs/api/",
    "type": "Gone",
    "error": true
}

I understand Overtone needs updating to the Freesound APIv2 (and OAuth2 authentication)
http://www.freesound.org/docs/api/authentication.html#oauth-authentication

**Comment by namin** [comment]
There's a pull request in progress here: https://github.com/overtone/overtone/pull/332

**Comment by namin** [comment]
It would be great if you would test it out. The easiest way is to checkout the branch https://github.com/namin/overtone/tree/freesound-apiv2, do `lein install` and then use version 0.10-SNAPSHOT in your projects.

**Comment by Mestelan** [comment]
It worked out of the box!  The app used is 
https://github.com/rogerallen/beatr

I was slightly puzzled by Emacs displaying "stdin" in the minibuffer, but the authentication process went smoothly.

Thank you so much.

**Comment by Quantisan** [comment]
thanks for the patch @namin

**Comment by Quantisan** [comment]
@namin do you have your branch on clojars?

**Comment by namin** [comment]
Glad it's working. I don't have the branch on clojars since I hope it can be merged. \cc @samaaron

**Comment by jave** [comment]
I also tested, and it works great!

**Comment by Quantisan** [comment]
I've pushed it to `[quantisan/overtone "0.10-SNAPSHOT"]`

**Comment by Mestelan** [comment]
Merged: 8b8353b27c

**Comment by ccorcos** [comment]
Hey there, I'm new to Clojure in general -- I changed the dependencies.
```
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [overtone "0.9.1"]])
```
I ran `lein install` and I still get this error

**Comment by Quantisan** [comment]
@ccorcos 0.9.1 don't have the fix yet, so is 0.10-SNAPSHOT. You'll have to use my fork `[quantisan/overtone "0.10-SNAPSHOT"]`

**Comment by ccorcos** [comment]
I see. doest that grab it straight from github? or are you publishing it to some package manager?

**Comment by Quantisan** [comment]
@ccorcos it grabs from clojars.org

**Comment by ccorcos** [comment]
awesome -- thanks!
